version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: unless-stopped

    user: "${JENKINS_UID:-1000}:${JENKINS_GID:-1000}"

    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      - JAVA_OPTS=-Duser.timezone=Europe/Budapest
      - JENKINS_OPTS=--prefix=/

    volumes:
      - jenkins_home:/var/jenkins_home
      - ${KUBECONFIG_HOST}:/var/jenkins_home/.kube:ro
      - /var/run/docker.sock:/var/run/docker.sock   # <<< EZ KELL!

    group_add:
      - "${DOCKER_GID}"

volumes:
  jenkins_home: {}
